services:

  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5000:3000"

  server-dev:
    build:
      context: ./server

    environment:
      NODE_ENV: development
    ports:
      - "3000:3000" 
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules


  mongo-dev:
    image: mongo:6-jammy
    ports:
      - "12345:27017"



  db-dev:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sql-squad-help-dev
    ports:
      - "12346:5432"

volumes:
  server-dev:
