services:

  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile-production
    ports:
      - "80:80"
    depends_on:
      - server-prod
    volumes_from:
      - server-prod:ro

  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile-production
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - db-prod
      - mongo-prod
    volumes:
      - /var/www/html/images:/var/www/html/images

  db-prod:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sql-squad-help-dev
    ports:
      - "12346:5432"

  mongo-prod:
    image: mongo:6-jammy
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "12345:27017"
    command: mongod --smallfiles --logpath=/dev/null

volumes:
  server-prod:
  # nginx-server-prod:
